// 2026-09-23 用户完成 W1 全量校对；保留当时确认的名称，源码变更后可重新标记待核对。
interface ReviewedDecision {
  kind: "blank" | "conflict" | "unreviewed";
  status: "confirmed" | "unclear";
  value: string;
}

export const reviewedDecisions: Record<string, ReviewedDecision> = {
  "W1-A1-01": { kind: "unreviewed", status: "confirmed", value: "Salt的展位" },
  "W1-A1-02": { kind: "unreviewed", status: "confirmed", value: "袋鼠海咪" },
  "W1-A1-03": { kind: "unreviewed", status: "confirmed", value: "三角耄" },
  "W1-A1-04": { kind: "blank", status: "confirmed", value: "三癞铺子" },
  "W1-A1-05": { kind: "unreviewed", status: "confirmed", value: "kemokemono" },
  "W1-A1-06": { kind: "unreviewed", status: "confirmed", value: "NightTalker摸鱼基地" },
  "W1-A1-07": { kind: "unreviewed", status: "confirmed", value: "Raven Studio" },
  "W1-A1-08": { kind: "unreviewed", status: "confirmed", value: "Ruithm" },
  "W1-A1-09": { kind: "unreviewed", status: "confirmed", value: "Sirens Inpart" },
  "W1-A1-10": { kind: "unreviewed", status: "confirmed", value: "zhenyitoys" },
  "W1-A1-11": { kind: "blank", status: "confirmed", value: "贡子&紫菜包饭" },
  "W1-A1-12": { kind: "blank", status: "confirmed", value: "赛博捏泥厨房" },
  "W1-A1-13": { kind: "blank", status: "confirmed", value: "模凹猫模型俱乐部" },
  "W1-A1-14": { kind: "unreviewed", status: "confirmed", value: "下班积极分子" },
  "W1-A1-15": { kind: "blank", status: "confirmed", value: "老张的模玩" },
  "W1-A2-01": { kind: "unreviewed", status: "confirmed", value: "银龙工坊" },
  "W1-A2-02": { kind: "unreviewed", status: "confirmed", value: "木下studio" },
  "W1-A2-03": { kind: "unreviewed", status: "confirmed", value: "ECHO喵喵屋" },
  "W1-A2-04": { kind: "blank", status: "confirmed", value: "怪泥猫咖" },
  "W1-A2-05": { kind: "unreviewed", status: "confirmed", value: "羽国志异" },
  "W1-A2-06": { kind: "blank", status: "confirmed", value: "靛柏工作室&奇物壔" },
  "W1-A2-07": { kind: "unreviewed", status: "confirmed", value: "GOA" },
  "W1-A2-08": { kind: "unreviewed", status: "confirmed", value: "STAR RISE/星升" },
  "W1-A2-09": { kind: "blank", status: "confirmed", value: "酱爆鸡米花月球工坊" },
  "W1-A2-10": { kind: "unreviewed", status: "confirmed", value: "小资历" },
  "W1-A2-11": { kind: "unreviewed", status: "confirmed", value: "至尊二次元" },
  "W1-A3-01": { kind: "unreviewed", status: "confirmed", value: "天格制造" },
  "W1-A3-02": { kind: "blank", status: "confirmed", value: "光魔殿" },
  "W1-A3-03": { kind: "unreviewed", status: "confirmed", value: "MusicBOX" },
  "W1-A3-04": { kind: "unreviewed", status: "confirmed", value: "自动约饭人偶" },
  "W1-A3-05": { kind: "unreviewed", status: "confirmed", value: "StratoStudio" },
  "W1-A4-01": { kind: "unreviewed", status: "confirmed", value: "MF6寸玩具工作室" },
  "W1-A4-02": { kind: "blank", status: "confirmed", value: "平無地工業" },
  "W1-A4-03": { kind: "blank", status: "confirmed", value: "乱成一锅粥喝了吧" },
  "W1-A4-04": { kind: "unreviewed", status: "confirmed", value: "乌托邦Utopia" },
  "W1-A4-05": { kind: "unreviewed", status: "confirmed", value: "拾川" },
  "W1-A4-06": { kind: "unreviewed", status: "confirmed", value: "27狱" },
  "W1-A4-07": { kind: "unreviewed", status: "confirmed", value: "zartstudio" },
  "W1-A4-08": { kind: "blank", status: "confirmed", value: "黄狮虎工坊" },
  "W1-A4-09": { kind: "unreviewed", status: "confirmed", value: "羽川_Wengn" },
  "W1-A4-10": { kind: "unreviewed", status: "confirmed", value: "九成新的饭盒" },
  "W1-A4-11": { kind: "unreviewed", status: "confirmed", value: "铁雄" },
  "W1-A4-12": { kind: "unreviewed", status: "confirmed", value: "白鸽" },
  "W1-A4-13": { kind: "unreviewed", status: "confirmed", value: "冷吃兔工作室" },
  "W1-A4-14": { kind: "blank", status: "confirmed", value: "☆好药丸★" },
  "W1-A4-15": { kind: "unreviewed", status: "confirmed", value: "救难英雄打击!" },
  "W1-A5-01": { kind: "unreviewed", status: "confirmed", value: "模玩" },
  "W1-A5-02": { kind: "blank", status: "confirmed", value: "腮红鸡厂" },
  "W1-A5-03": { kind: "unreviewed", status: "confirmed", value: "柚子叉" },
  "W1-A5-04": { kind: "unreviewed", status: "confirmed", value: "粉匠" },
  "W1-A5-05": { kind: "blank", status: "confirmed", value: "界限连结" },
  "W1-A5-06": { kind: "unreviewed", status: "confirmed", value: "四夜的小屋" },
  "W1-A5-07": { kind: "blank", status: "confirmed", value: "左又烦恼" },
  "W1-A5-08": { kind: "unreviewed", status: "confirmed", value: "kukuna" },
  "W1-A5-09": { kind: "unreviewed", status: "confirmed", value: "CALBONE" },
  "W1-A5-10": { kind: "unreviewed", status: "confirmed", value: "LAS漫研" },
  "W1-A5-11": { kind: "unreviewed", status: "confirmed", value: "Studio Guys" },
  "W1-A5-12": { kind: "unreviewed", status: "confirmed", value: "ZERO-MAX" },
  "W1-A5-13": { kind: "blank", status: "confirmed", value: "夜晚的长颈鹿不会Revue" },
  "W1-A5-14": { kind: "blank", status: "confirmed", value: "塔可" },
  "W1-A5-15": { kind: "blank", status: "confirmed", value: "迷宫塔联盟" },
  "W1-A5-16": { kind: "blank", status: "confirmed", value: "QR庆荣模玩" },
  "W1-A6-01": { kind: "unreviewed", status: "confirmed", value: "紙飛行機" },
  "W1-A6-02": { kind: "unreviewed", status: "confirmed", value: "迷因工作室" },
  "W1-A6-03": { kind: "unreviewed", status: "confirmed", value: "昭阳微缩" },
  "W1-A6-04": { kind: "unreviewed", status: "confirmed", value: "WizardWorks" },
  "W1-A6-05": { kind: "unreviewed", status: "confirmed", value: "鱼宝玩具" },
  "W1-A6-06": { kind: "unreviewed", status: "confirmed", value: "黄昏熔融DUSKMELT" },
  "W1-A6-07": { kind: "unreviewed", status: "confirmed", value: "重力前线动漫社模型部" },
  "W1-A6-08": { kind: "unreviewed", status: "confirmed", value: "AXIS工作室展品" },
  "W1-A6-09": { kind: "blank", status: "confirmed", value: "咕嘎咕嘎" },
  "W1-A7-01": { kind: "unreviewed", status: "confirmed", value: "水口钳模型" },
  "W1-A7-02": { kind: "unreviewed", status: "confirmed", value: "小鸟模型" },
  "W1-A7-03": { kind: "unreviewed", status: "confirmed", value: "形投艺合工作室" },
  "W1-A7-04": { kind: "blank", status: "confirmed", value: "战斧创造 幻想工业" },
  "W1-A7-05": { kind: "unreviewed", status: "confirmed", value: "rain" },
  "W1-A7-06": { kind: "unreviewed", status: "confirmed", value: "果果社" },
  "W1-A7-07": { kind: "unreviewed", status: "confirmed", value: "幽蓦文化" },
  "W1-A7-08": { kind: "unreviewed", status: "confirmed", value: "紫云微模型" },
  "W1-A7-09": { kind: "unreviewed", status: "confirmed", value: "AMIA" },
  "W1-A7-10": { kind: "unreviewed", status: "confirmed", value: "Cecishi Dumbo" },
  "W1-B1-01": { kind: "unreviewed", status: "confirmed", value: "方橙士FCS" },
  "W1-B1-02": { kind: "unreviewed", status: "confirmed", value: "怪力乱涂" },
  "W1-B1-03": { kind: "unreviewed", status: "confirmed", value: "光叔叔的夜叉坞" },
  "W1-B1-04": { kind: "unreviewed", status: "confirmed", value: "黑帆Studio" },
  "W1-B1-05": { kind: "unreviewed", status: "confirmed", value: "黑金博物馆" },
  "W1-B1-06": { kind: "unreviewed", status: "confirmed", value: "胡老爷的马戏团" },
  "W1-B1-07": { kind: "unreviewed", status: "confirmed", value: "吉娃娃宇宙" },
  "W1-B1-08": { kind: "unreviewed", status: "confirmed", value: "蓝波大人" },
  "W1-B1-09": { kind: "unreviewed", status: "confirmed", value: "良之手作潮玩木雕" },
  "W1-B1-10": { kind: "unreviewed", status: "confirmed", value: "零二原创工作室" },
  "W1-B1-11": { kind: "unreviewed", status: "confirmed", value: "榴莲萌宠" },
  "W1-B1-12": { kind: "unreviewed", status: "confirmed", value: "霉霉和口可の粘土集" },
  "W1-B1-13": { kind: "unreviewed", status: "confirmed", value: "摸鱼工作室" },
  "W1-B2-01": { kind: "unreviewed", status: "confirmed", value: "东来也" },
  "W1-B2-02": { kind: "unreviewed", status: "confirmed", value: "大怪动物园" },
  "W1-B2-03": { kind: "unreviewed", status: "confirmed", value: "达达拉DADALA" },
  "W1-B2-04": { kind: "unreviewed", status: "confirmed", value: "大连东软信息学院" },
  "W1-B2-05": { kind: "unreviewed", status: "confirmed", value: "墩墩儿小王国" },
  "W1-B2-06": { kind: "unreviewed", status: "confirmed", value: "格派匠艺" },
  "W1-B3-01": { kind: "unreviewed", status: "confirmed", value: "ZZZ-X MONSTER" },
  "W1-B3-02": { kind: "unreviewed", status: "confirmed", value: "贝吉旺" },
  "W1-B3-03": { kind: "unreviewed", status: "confirmed", value: "博达" },
  "W1-B3-04": { kind: "unreviewed", status: "confirmed", value: "创伤收容处_TCCU" },
  "W1-B3-05": { kind: "unreviewed", status: "confirmed", value: "百目白" },
  "W1-B3-06": { kind: "unreviewed", status: "confirmed", value: "千机冢" },
  "W1-B3-07": { kind: "unreviewed", status: "confirmed", value: "BENDAN俱乐部" },
  "W1-B3-08": { kind: "unreviewed", status: "confirmed", value: "DRWORKS" },
  "W1-B3-09": { kind: "unreviewed", status: "confirmed", value: "捣蛋制造" },
  "W1-B4-01": { kind: "unreviewed", status: "confirmed", value: "旭旸亿物商贸（上海）有限公司" },
  "W1-B4-02": { kind: "unreviewed", status: "confirmed", value: "悟空印象" },
  "W1-B4-03": { kind: "unreviewed", status: "unclear", value: "" },
  "W1-B4-04": { kind: "unreviewed", status: "confirmed", value: "洋葱Cycle" },
  "W1-B4-05": { kind: "unreviewed", status: "confirmed", value: "宇宙漫游乘务中心" },
  "W1-B4-06": { kind: "unreviewed", status: "confirmed", value: "BLUE BOBCAT" },
  "W1-B4-07": { kind: "unreviewed", status: "confirmed", value: "Crazy Lab" },
  "W1-B4-08": { kind: "unreviewed", status: "confirmed", value: "Fini's Workshop" },
  "W1-B4-09": { kind: "unreviewed", status: "confirmed", value: "GOOGOOGAAGAA" },
  "W1-B4-10": { kind: "unreviewed", status: "confirmed", value: "GROUND CONTROL" },
  "W1-B4-11": { kind: "unreviewed", status: "confirmed", value: "Laffo來福玩具" },
  "W1-B4-12": { kind: "unreviewed", status: "confirmed", value: "LALA COMPANY" },
  "W1-B4-13": { kind: "unreviewed", status: "confirmed", value: "MADE BY FAN&FANTOYS" },
  "W1-B4-14": { kind: "unreviewed", status: "confirmed", value: "MZ小卖部" },
  "W1-B4-15": { kind: "unreviewed", status: "confirmed", value: "QBOOM萌核邦" },
  "W1-B5-01": { kind: "unreviewed", status: "confirmed", value: "RadioRat电台老鼠" },
  "W1-B5-02": { kind: "unreviewed", status: "confirmed", value: "Sensation Studio" },
  "W1-B5-03": { kind: "unreviewed", status: "confirmed", value: "WIOFY的小卖部" },
  "W1-B5-04": { kind: "unreviewed", status: "confirmed", value: "YeeesToday" },
  "W1-B5-05": { kind: "unreviewed", status: "confirmed", value: "爆炸小妮x涂装博士" },
  "W1-B5-06": { kind: "unreviewed", status: "confirmed", value: "电子星公民" },
  "W1-B5-07": { kind: "unreviewed", status: "confirmed", value: "饭团计划" },
  "W1-B5-08": { kind: "unreviewed", status: "confirmed", value: "匠喵" },
  "W1-B5-09": { kind: "unreviewed", status: "confirmed", value: "金羚公社" },
  "W1-B5-10": { kind: "unreviewed", status: "confirmed", value: "空想造物" },
  "W1-B5-11": { kind: "unreviewed", status: "confirmed", value: "六分之五" },
  "W1-B5-12": { kind: "blank", status: "confirmed", value: "桶一&奇离古怪研究中心" },
  "W1-B5-13": { kind: "unreviewed", status: "confirmed", value: "稀奇百货" },
  "W1-B5-14": { kind: "unreviewed", status: "confirmed", value: "蒸汽工厂STEAMARTS" },
  "W1-B5-15": { kind: "unreviewed", status: "confirmed", value: "子鱼不器" },
  "W1-B5-16": { kind: "unreviewed", status: "confirmed", value: "Beeking" },
  "W1-B5-17": { kind: "unreviewed", status: "confirmed", value: "CC小窝" },
  "W1-B6-01": { kind: "unreviewed", status: "confirmed", value: "dodowo" },
  "W1-B6-02": { kind: "unreviewed", status: "confirmed", value: "HOTRU STUDIO" },
  "W1-B6-03": { kind: "unreviewed", status: "confirmed", value: "ICE HOLE" },
  "W1-B6-04": { kind: "unreviewed", status: "confirmed", value: "I'm Nono" },
  "W1-B6-05": { kind: "unreviewed", status: "confirmed", value: "J STUDIO&KODAMAGO" },
  "W1-B6-06": { kind: "unreviewed", status: "confirmed", value: "JUJU&MVOS" },
  "W1-B6-07": { kind: "blank", status: "confirmed", value: "MiBOO town 16人格盲盒 X kuri栗子菌" },
  "W1-B6-08": { kind: "unreviewed", status: "confirmed", value: "NUTCRACKXXX" },
  "W1-B6-09": { kind: "unreviewed", status: "confirmed", value: "PB TOY DESIGN" },
  "W1-B6-10": { kind: "unreviewed", status: "confirmed", value: "PLAYCORE 凭空幻想" },
  "W1-B6-11": { kind: "unreviewed", status: "confirmed", value: "PTUNIS铂宙宇" },
  "W1-B6-12": { kind: "unreviewed", status: "confirmed", value: "Toysmaoo" },
  "W1-B6-13": { kind: "unreviewed", status: "confirmed", value: "WY琢梦" },
  "W1-B6-14": { kind: "unreviewed", status: "confirmed", value: "zhizhi涂装工作室" },
  "W1-B6-15": { kind: "unreviewed", status: "confirmed", value: "ZNTOYS" },
  "W1-B6-16": { kind: "unreviewed", status: "confirmed", value: "凹凸好朋友" },
  "W1-B7-01": { kind: "unreviewed", status: "confirmed", value: "奇形堂" },
  "W1-B7-02": { kind: "unreviewed", status: "confirmed", value: "茸屋" },
  "W1-B7-03": { kind: "unreviewed", status: "confirmed", value: "散物集" },
  "W1-B7-04": { kind: "unreviewed", status: "confirmed", value: "双岛" },
  "W1-B7-05": { kind: "blank", status: "confirmed", value: "设屋攻業®" },
  "W1-B7-06": { kind: "unreviewed", status: "confirmed", value: "太乙TOYSCOMIC" },
  "W1-C1-01": { kind: "conflict", status: "confirmed", value: "黑莲工作室" },
  "W1-C1-02": { kind: "conflict", status: "confirmed", value: "沧溟工作室" },
  "W1-C1-03": { kind: "unreviewed", status: "confirmed", value: "OMAHA" },
  "W1-C1-04": { kind: "unreviewed", status: "confirmed", value: "XD快乐烧酒屋" },
  "W1-C1-05": { kind: "unreviewed", status: "confirmed", value: "李想不画画" },
  "W1-C1-06": { kind: "unreviewed", status: "confirmed", value: "Dapan_Studio" },
  "W1-C1-07": { kind: "unreviewed", status: "confirmed", value: "WHSND" },
  "W1-C1-08": { kind: "blank", status: "confirmed", value: "阿KeikMO模玩处" },
  "W1-C1-09": { kind: "unreviewed", status: "confirmed", value: "椿木镇" },
  "W1-C1-10": { kind: "blank", status: "confirmed", value: "呆鸽和老戴的模型时间" },
  "W1-C1-11": { kind: "unreviewed", status: "confirmed", value: "老孙-BLURyu" },
  "W1-C2-01": { kind: "unreviewed", status: "confirmed", value: "涂鸦十号——泽夜" },
  "W1-C2-02": { kind: "unreviewed", status: "confirmed", value: "涂装动物园" },
  "W1-C2-03": { kind: "blank", status: "confirmed", value: "未这散散" },
  "W1-C2-04": { kind: "unreviewed", status: "confirmed", value: "斜眼龙神" },
  "W1-C2-05": { kind: "blank", status: "confirmed", value: "星澜奇物坊" },
  "W1-C2-06": { kind: "unreviewed", status: "confirmed", value: "牙仙工作室ToothFairyStudio" },
  "W1-C2-07": { kind: "blank", status: "confirmed", value: "洋大朋友/欧润几org" },
  "W1-C2-08": { kind: "unreviewed", status: "confirmed", value: "妖-YAO SELFE" },
  "W1-C2-09": { kind: "unreviewed", status: "confirmed", value: "异界轶闻" },
  "W1-C2-10": { kind: "unreviewed", status: "confirmed", value: "遠東漁業保護協會" },
  "W1-C2-11": { kind: "unreviewed", status: "confirmed", value: "造物口袋" },
  "W1-C2-12": { kind: "blank", status: "confirmed", value: "臻模造物" },
  "W1-C2-13": { kind: "unreviewed", status: "confirmed", value: "自我魔型坞" },
  "W1-C3-01": { kind: "blank", status: "confirmed", value: "神铸庭" },
  "W1-C3-02": { kind: "unreviewed", status: "confirmed", value: "石头左手" },
  "W1-C3-03": { kind: "unreviewed", status: "confirmed", value: "束泼YUKANG LI" },
  "W1-C3-04": { kind: "unreviewed", status: "confirmed", value: "青模社等身手办" },
  "W1-C3-05": { kind: "blank", status: "confirmed", value: "如己工作室《蛇含》" },
  "W1-C3-06": { kind: "blank", status: "confirmed", value: "弱酸型幻想工坊" },
  "W1-C3-07": { kind: "blank", status: "confirmed", value: "叁仟造物工作室" },
  "W1-C3-08": { kind: "unreviewed", status: "confirmed", value: "松雾草与jojo&miumiu" },
  "W1-C3-09": { kind: "blank", status: "confirmed", value: "酸菜宝和罐头鱼" },
  "W1-C4-01": { kind: "unreviewed", status: "confirmed", value: "黑光" },
  "W1-C4-02": { kind: "unreviewed", status: "confirmed", value: "科达三维&TOYES" },
  "W1-C4-03": { kind: "unreviewed", status: "confirmed", value: "Ssky天天" },
  "W1-C4-04": { kind: "unreviewed", status: "confirmed", value: "白泽手作" },
  "W1-C4-05": { kind: "unreviewed", status: "confirmed", value: "翡翠梦境" },
  "W1-C4-06": { kind: "blank", status: "confirmed", value: "丧钟重涂" },
  "W1-C4-07": { kind: "unreviewed", status: "confirmed", value: "山羽 X TCFSTUDIO" },
  "W1-C4-08": { kind: "blank", status: "confirmed", value: "失业老狗卖模摊" },
  "W1-C4-09": { kind: "unreviewed", status: "confirmed", value: "五柳" },
  "W1-C4-10": { kind: "unreviewed", status: "confirmed", value: "小手一挥工作室" },
  "W1-C4-11": { kind: "unreviewed", status: "confirmed", value: "游云仙画" },
  "W1-C4-12": { kind: "unreviewed", status: "confirmed", value: "蒸蛋TOYS" },
  "W1-C4-13": { kind: "unreviewed", status: "confirmed", value: "中国神话系列雕像" },
  "W1-C4-14": { kind: "unreviewed", status: "confirmed", value: "熊猫工作室" },
  "W1-C4-15": { kind: "unreviewed", status: "confirmed", value: "天风工作室" },
  "W1-C5-01": { kind: "unreviewed", status: "confirmed", value: "阿画的小摊" },
  "W1-C5-02": { kind: "unreviewed", status: "confirmed", value: "憨憨喵工作室" },
  "W1-C5-03": { kind: "blank", status: "confirmed", value: "爬poa_Pa" },
  "W1-C5-04": { kind: "unreviewed", status: "confirmed", value: "宝宝你涂的好棒" },
  "W1-C5-05": { kind: "blank", status: "confirmed", value: "抱水少女与邪恶蛋蛋虫" },
  "W1-C5-06": { kind: "blank", status: "confirmed", value: "厄尔菲斯oc展示" },
  "W1-C5-07": { kind: "unreviewed", status: "confirmed", value: "黑猫" },
  "W1-C5-08": { kind: "unreviewed", status: "confirmed", value: "黑匣工作室" },
  "W1-C5-09": { kind: "unreviewed", status: "confirmed", value: "末那众合" },
  "W1-C5-10": { kind: "unreviewed", status: "confirmed", value: "幻鳞化翼工作室" },
  "W1-C5-11": { kind: "blank", status: "confirmed", value: "缄默月震" },
  "W1-C5-12": { kind: "unreviewed", status: "confirmed", value: "橘汽乐玩" },
  "W1-C5-13": { kind: "unreviewed", status: "confirmed", value: "李师傅涂装" },
  "W1-C6-01": { kind: "blank", status: "confirmed", value: "Athena:X阿忒娜手办" },
  "W1-C6-02": { kind: "unreviewed", status: "confirmed", value: "Animeone" },
  "W1-C6-03": { kind: "unreviewed", status: "confirmed", value: "Blossom Tea Party" },
  "W1-C6-04": { kind: "unreviewed", status: "confirmed", value: "Crazy Cube" },
  "W1-C6-05": { kind: "unreviewed", status: "confirmed", value: "Crimson Dream Atelier绯梦工房" },
  "W1-C6-06": { kind: "unreviewed", status: "confirmed", value: "DCTer" },
  "W1-C6-07": { kind: "unreviewed", status: "confirmed", value: "PUZZLE" },
  "W1-C6-08": { kind: "unreviewed", status: "confirmed", value: "ECHO" },
  "W1-C6-09": { kind: "unreviewed", status: "confirmed", value: "North" },
  "W1-C6-10": { kind: "unreviewed", status: "confirmed", value: "OuYou欧阳" },
  "W1-C6-11": { kind: "unreviewed", status: "confirmed", value: "Peileft" },
  "W1-C6-12": { kind: "unreviewed", status: "confirmed", value: "PinkBlood" },
  "W1-C7-01": { kind: "unreviewed", status: "confirmed", value: "FANKIT" },
  "W1-C7-02": { kind: "conflict", status: "confirmed", value: "FIROWITO" },
  "W1-C7-03": { kind: "unreviewed", status: "confirmed", value: "K_K_studios" },
  "W1-C7-04": { kind: "unreviewed", status: "confirmed", value: "KK脑袋日记·手作" },
  "W1-C7-05": { kind: "unreviewed", status: "confirmed", value: "Minority" },
  "W1-C7-06": { kind: "unreviewed", status: "confirmed", value: "MLAN STUDIO" },
  "W1-C7-07": { kind: "unreviewed", status: "confirmed", value: "Pc.Maker" },
  "W1-C7-08": { kind: "unreviewed", status: "confirmed", value: "Rainsun 雨阳" },
  "W1-C7-09": { kind: "unreviewed", status: "confirmed", value: "SIVA 3D游戏手办工作室" },
  "W1-C7-10": { kind: "unreviewed", status: "confirmed", value: "studioQUE" },
  "W1-C7-11": { kind: "blank", status: "confirmed", value: "VVXIE和麻辣猫" },
  "W1-C7-12": { kind: "unreviewed", status: "confirmed", value: "Team Bacon" },
  "W1-D1-01": { kind: "conflict", status: "confirmed", value: "MOJING TOYS 模镜工作室" },
  "W1-D1-02": { kind: "unreviewed", status: "confirmed", value: "末途手作" },
  "W1-D1-03": { kind: "unreviewed", status: "confirmed", value: "OriStone原石盒子" },
  "W1-D1-04": { kind: "blank", status: "confirmed", value: "日映工房/重力熊星" },
  "W1-D1-05": { kind: "unreviewed", status: "confirmed", value: "未纳工作室" },
  "W1-D1-06": { kind: "blank", status: "confirmed", value: "玩巨窝" },
  "W1-D1-07": { kind: "unreviewed", status: "confirmed", value: "妖子工坊" },
  "W1-D1-08": { kind: "blank", status: "confirmed", value: "驻猫小屋X伪信朋克" },
  "W1-D1-09": { kind: "blank", status: "confirmed", value: "猩岚工坊模玩" },
  "W1-D1-10": { kind: "blank", status: "confirmed", value: "鸢槿智能" },
  "W1-D1-11": { kind: "unreviewed", status: "confirmed", value: "自给" },
  "W1-D2-01": { kind: "unreviewed", status: "confirmed", value: "布叽岛" },
  "W1-D2-02": { kind: "unreviewed", status: "confirmed", value: "原力智造" },
  "W1-D2-03": { kind: "unreviewed", status: "confirmed", value: "M7的展位" },
  "W1-D2-04": { kind: "unreviewed", status: "confirmed", value: "MINOR technology" },
  "W1-D2-05": { kind: "unreviewed", status: "confirmed", value: "Time Line工作室" },
  "W1-D2-06": { kind: "unreviewed", status: "confirmed", value: "YELLOW BUS!" },
  "W1-D2-07": { kind: "blank", status: "confirmed", value: "阿幻海姆战术机制造厂" },
  "W1-D2-08": { kind: "unreviewed", status: "confirmed", value: "GM模型" },
  "W1-D2-09": { kind: "unreviewed", status: "confirmed", value: "Zero-Type 零式模型" },
  "W1-D2-10": { kind: "blank", status: "confirmed", value: "白蛾" },
  "W1-D2-11": { kind: "unreviewed", status: "confirmed", value: "飞宇工业" },
  "W1-D2-12": { kind: "unreviewed", status: "confirmed", value: "幻星重工" },
  "W1-D3-01": { kind: "unreviewed", status: "confirmed", value: "GOE YON霜云工作室" },
  "W1-D3-02": { kind: "unreviewed", status: "confirmed", value: "造物志&zoe手作" },
  "W1-D3-03": { kind: "conflict", status: "confirmed", value: "长脚犀studio" },
  "W1-D3-04": { kind: "unreviewed", status: "confirmed", value: "左转十七" },
  "W1-D3-05": { kind: "unreviewed", status: "confirmed", value: "stedi司特力" },
  "W1-D3-06": { kind: "unreviewed", status: "confirmed", value: "裕泽模型" },
  "W1-D3-07": { kind: "unreviewed", status: "confirmed", value: "懒懒同学" },
  "W1-D3-08": { kind: "unreviewed", status: "confirmed", value: "小明工具铺/剑修心" },
  "W1-D3-09": { kind: "unreviewed", status: "confirmed", value: "遮易速预裁切遮盖" },
  "W1-D4-01": { kind: "unreviewed", status: "confirmed", value: "白血工铸" },
  "W1-D4-02": {
    kind: "unreviewed",
    status: "confirmed",
    value: "炽星工作室 Blazing Galaxy Studio",
  },
  "W1-D4-03": { kind: "conflict", status: "confirmed", value: "钢铁浪漫制造所" },
  "W1-D4-04": { kind: "unreviewed", status: "confirmed", value: "三个大蓝龙" },
  "W1-D4-05": { kind: "unreviewed", status: "confirmed", value: "LJ Koh" },
  "W1-D4-06": { kind: "blank", status: "confirmed", value: "MWxBFG" },
  "W1-D4-07": { kind: "unreviewed", status: "confirmed", value: "坦克莱德" },
  "W1-D4-08": { kind: "unreviewed", status: "confirmed", value: "坦桑石设计局" },
  "W1-D4-09": { kind: "unreviewed", status: "confirmed", value: "阿古研究所" },
  "W1-D4-10": { kind: "conflict", status: "confirmed", value: "黑砖工作室" },
  "W1-D4-11": { kind: "unreviewed", status: "confirmed", value: "明月松间" },
  "W1-D5-01": { kind: "blank", status: "confirmed", value: "钰的堆积" },
  "W1-D5-02": { kind: "unreviewed", status: "confirmed", value: "星辰回忆" },
  "W1-D5-03": { kind: "unreviewed", status: "confirmed", value: "痒窝" },
  "W1-D5-04": { kind: "unreviewed", status: "confirmed", value: "夜之工坊X大火鸟制造" },
  "W1-D5-05": { kind: "unreviewed", status: "confirmed", value: "宅猫工作室" },
  "W1-D5-06": { kind: "unreviewed", status: "confirmed", value: "浪人犬工作室" },
  "W1-D5-07": { kind: "blank", status: "confirmed", value: "珠海机甲天下科技有限公司" },
  "W1-D6-01": { kind: "unreviewed", status: "confirmed", value: "小样儿3D" },
  "W1-D6-02": { kind: "blank", status: "confirmed", value: "机域研具" },
  "W1-D6-03": { kind: "unreviewed", status: "confirmed", value: "来福特的奇思妙想" },
  "W1-D6-04": { kind: "unreviewed", status: "confirmed", value: "模笛Molycraft" },
  "W1-D6-05": { kind: "unreviewed", status: "confirmed", value: "模鲨" },
  "W1-D6-06": { kind: "unreviewed", status: "confirmed", value: "轻度沸腾" },
  "W1-D6-07": { kind: "unreviewed", status: "confirmed", value: "内鬼交易" },
  "W1-D6-08": { kind: "unreviewed", status: "confirmed", value: "大肚子工作室" },
  "W1-D6-09": { kind: "unreviewed", status: "confirmed", value: "全开工作室" },
  "W1-D6-10": { kind: "unreviewed", status: "confirmed", value: "如果胶囊 If Capsule Studio" },
  "W1-D6-11": { kind: "unreviewed", status: "confirmed", value: "三眛模玩" },
  "W1-D6-12": { kind: "unreviewed", status: "confirmed", value: "三十三号工厂" },
  "W1-D6-13": { kind: "unreviewed", status: "confirmed", value: "维度重工" },
  "W1-D6-14": { kind: "unreviewed", status: "confirmed", value: "无用工业" },
  "W1-D6-15": { kind: "unreviewed", status: "confirmed", value: "武士工坊&玩雾" },
  "W1-D7-01": { kind: "blank", status: "confirmed", value: "魍魉斋" },
  "W1-D7-02": { kind: "unreviewed", status: "confirmed", value: "有矿" },
  "W1-D7-03": { kind: "unreviewed", status: "confirmed", value: "北京八脚工作室" },
  "W1-D7-04": { kind: "unreviewed", status: "confirmed", value: "言己造物" },
  "W1-D7-05": { kind: "unreviewed", status: "confirmed", value: "一川艺术" },
  "W1-D7-06": { kind: "unreviewed", status: "confirmed", value: "BinJie.Lee" },
  "W1-D8-01": { kind: "unreviewed", status: "confirmed", value: "the wall" },
  "W1-D8-02": { kind: "blank", status: "confirmed", value: "獭獭开" },
  "W1-D8-03": { kind: "unreviewed", status: "confirmed", value: "海怪游戏营地" },
  "W1-D8-04": { kind: "unreviewed", status: "confirmed", value: "吃货饱饱" },
  "W1-D8-05": { kind: "unreviewed", status: "confirmed", value: "机甲键帽Johnny" },
  "W1-D8-06": { kind: "blank", status: "confirmed", value: "膨膨制造局" },
  "W1-D8-07": { kind: "blank", status: "confirmed", value: "濮阳市峰创三围科技有限公司" },
  "W1-D8-08": { kind: "unreviewed", status: "confirmed", value: "球不圆" },
  "W1-D8-09": { kind: "unreviewed", status: "confirmed", value: "双氧水" },
  "W1-D8-10": { kind: "conflict", status: "confirmed", value: "溯源工作室" },
  "W1-E1-01": { kind: "unreviewed", status: "confirmed", value: "赛博灵宠CyberPet" },
  "W1-E1-02": { kind: "unreviewed", status: "confirmed", value: "十万火吉" },
  "W1-E1-03": { kind: "unreviewed", status: "confirmed", value: "须弥工作室" },
  "W1-E1-04": { kind: "unreviewed", status: "confirmed", value: "拾荒记" },
  "W1-E1-05": { kind: "blank", status: "confirmed", value: "是瑞鹿呀" },
  "W1-E1-06": { kind: "unreviewed", status: "confirmed", value: "肆月甲虫" },
  "W1-E1-07": { kind: "unreviewed", status: "confirmed", value: "心上猫" },
  "W1-E1-08": { kind: "unreviewed", status: "confirmed", value: "吾造WUZAO" },
  "W1-E1-09": { kind: "conflict", status: "confirmed", value: "小虫趣玩" },
  "W1-E1-10": { kind: "unreviewed", status: "confirmed", value: "星辰海标本工作室" },
  "W1-E2-01": { kind: "unreviewed", status: "confirmed", value: "涅槃模型工作室" },
  "W1-E2-02": { kind: "unreviewed", status: "confirmed", value: "啪嗒啪嗒" },
  "W1-E2-03": { kind: "unreviewed", status: "confirmed", value: "龙零" },
  "W1-E2-04": { kind: "unreviewed", status: "confirmed", value: "叁个喵氛" },
  "W1-E2-05": { kind: "unreviewed", status: "confirmed", value: "生息文创坊" },
  "W1-E2-06": { kind: "unreviewed", status: "confirmed", value: "十四日模型工作室" },
  "W1-E2-07": { kind: "unreviewed", status: "confirmed", value: "青山自然" },
  "W1-E3-01": { kind: "blank", status: "confirmed", value: "光春闸蟹cgctoys" },
  "W1-E3-02": { kind: "unreviewed", status: "confirmed", value: "动物星云" },
  "W1-E3-03": { kind: "unreviewed", status: "confirmed", value: "模捞捞FIGURERICH" },
  "W1-E3-04": { kind: "unreviewed", status: "confirmed", value: "躲猫猫行动" },
  "W1-E3-05": { kind: "conflict", status: "confirmed", value: "集奇怪—世界昆虫" },
  "W1-E3-06": { kind: "blank", status: "confirmed", value: "观罐" },
  "W1-E3-07": { kind: "unreviewed", status: "confirmed", value: "海洋理想国" },
  "W1-E3-08": { kind: "unreviewed", status: "confirmed", value: "木刻自习室" },
  "W1-E4-01": { kind: "unreviewed", status: "confirmed", value: "天天头不大" },
  "W1-E4-02": { kind: "unreviewed", status: "confirmed", value: "显若工作室" },
  "W1-E4-03": { kind: "unreviewed", status: "confirmed", value: "小不悲和小不喜" },
  "W1-E4-04": { kind: "blank", status: "confirmed", value: "自明紫砂美学" },
  "W1-E4-05": { kind: "unreviewed", status: "confirmed", value: "BUDDHACAT & HAPPY RONY" },
  "W1-E4-06": { kind: "unreviewed", status: "confirmed", value: "PiaoOOOo Studio" },
  "W1-E4-07": { kind: "unreviewed", status: "confirmed", value: "THSL-SMB" },
  "W1-E4-08": { kind: "unreviewed", status: "confirmed", value: "Dream Brick" },
  "W1-E4-09": { kind: "unreviewed", status: "confirmed", value: "百川模型" },
  "W1-E4-10": { kind: "unreviewed", status: "confirmed", value: "库造工作室" },
  "W1-E4-11": { kind: "blank", status: "confirmed", value: "热狗积木MOC" },
  "W1-E4-12": { kind: "unreviewed", status: "confirmed", value: "凸凸凸积木MOC" },
  "W1-E4-13": { kind: "unreviewed", status: "confirmed", value: "Yanchstar" },
  "W1-E4-14": { kind: "unreviewed", status: "confirmed", value: "YYF原型工作室" },
  "W1-E5-01": { kind: "unreviewed", status: "confirmed", value: "APHID STUDIO" },
  "W1-E5-02": { kind: "unreviewed", status: "confirmed", value: "Brain Juice" },
  "W1-E5-03": { kind: "conflict", status: "confirmed", value: "JC家の玩具铺子" },
  "W1-E5-04": { kind: "unreviewed", status: "confirmed", value: "JIZAI!极哉!" },
  "W1-E5-05": { kind: "unreviewed", status: "confirmed", value: "KOODD" },
  "W1-E5-06": { kind: "unreviewed", status: "confirmed", value: "Prehistoricgarage" },
  "W1-E5-07": { kind: "unreviewed", status: "confirmed", value: "R3D Effects" },
  "W1-E5-08": { kind: "unreviewed", status: "confirmed", value: "阿慈" },
  "W1-E5-09": { kind: "unreviewed", status: "confirmed", value: "白昼" },
  "W1-E5-10": { kind: "unreviewed", status: "confirmed", value: "本博仿生" },
  "W1-E5-11": { kind: "unreviewed", status: "confirmed", value: "不吃饭工作室" },
  "W1-E5-12": { kind: "unreviewed", status: "confirmed", value: "大熊" },
  "W1-E6-01": { kind: "unreviewed", status: "confirmed", value: "造物之心" },
  "W1-E6-02": { kind: "conflict", status: "confirmed", value: "TinyFox小小狐" },
  "W1-E6-03": { kind: "unreviewed", status: "confirmed", value: "DollGalaxy星辉" },
  "W1-E6-04": { kind: "unreviewed", status: "confirmed", value: "dollzone" },
  "W1-E6-05": { kind: "unreviewed", status: "confirmed", value: "ElementDoll元素人形社" },
  "W1-E6-06": { kind: "unreviewed", status: "confirmed", value: "MiraLab幻象实验室" },
  "W1-E6-07": { kind: "unreviewed", status: "confirmed", value: "Oi 集社" },
  "W1-E6-08": { kind: "unreviewed", status: "confirmed", value: "ufdoll" },
  "W1-E6-09": { kind: "unreviewed", status: "confirmed", value: "可爱鬼故事" },
  "W1-E6-10": { kind: "unreviewed", status: "confirmed", value: "六角箱HEX BOX" },
  "W1-E6-11": { kind: "unreviewed", status: "confirmed", value: "人类发明家" },
  "W1-E6-12": { kind: "unreviewed", status: "confirmed", value: "向闪耀进发·燃星计划" },
  "W1-E7-01": { kind: "unreviewed", status: "confirmed", value: "团子星人" },
  "W1-E7-02": { kind: "blank", status: "confirmed", value: "无所:D谓" },
  "W1-E7-03": { kind: "unreviewed", status: "confirmed", value: "铁拳匠造" },
  "W1-E7-04": { kind: "unreviewed", status: "confirmed", value: "无限模境OTAKU ZONE" },
  "W1-E8-01": { kind: "unreviewed", status: "confirmed", value: "YADOL MICOL鸦逗玩具" },
  "W1-E8-02": { kind: "unreviewed", status: "confirmed", value: "布夭夭BUYAOY" },
  "W1-E8-03": { kind: "conflict", status: "confirmed", value: "碓冰拓海手作" },
  "W1-E8-04": { kind: "unreviewed", status: "confirmed", value: "黑锤HI CRAFT" },
  "W1-E8-05": { kind: "unreviewed", status: "confirmed", value: "霍皮波拉" },
  "W1-E8-06": { kind: "unreviewed", status: "confirmed", value: "围场猫咪" },
  "W1-E8-07": { kind: "conflict", status: "confirmed", value: "鲨鲨豆的毛茸动物世界" },
  "W1-E8-08": { kind: "unreviewed", status: "confirmed", value: "黑白灰小狗" },
  "W1-E8-09": { kind: "unreviewed", status: "confirmed", value: "爱谷酱" },
  "W1-E8-10": { kind: "unreviewed", status: "confirmed", value: "DREAM境" },
  "W1-E8-11": { kind: "conflict", status: "confirmed", value: "kozoostudio" },
  "W1-E8-12": { kind: "unreviewed", status: "confirmed", value: "YAAM studio" },
  "W1-E8-13": { kind: "unreviewed", status: "confirmed", value: "伴岛体" },
  "W1-F1-01": { kind: "unreviewed", status: "confirmed", value: "AceFigz" },
  "W1-F1-02": { kind: "unreviewed", status: "confirmed", value: "A社" },
  "W1-F1-03": { kind: "unreviewed", status: "confirmed", value: "Asiinak" },
  "W1-F1-04": { kind: "unreviewed", status: "confirmed", value: "BEN" },
  "W1-F1-05": { kind: "unreviewed", status: "confirmed", value: "blacklist" },
  "W1-F1-06": { kind: "unreviewed", status: "confirmed", value: "CYH工坊" },
  "W1-F1-07": { kind: "unreviewed", status: "confirmed", value: "DeepMythStudio" },
  "W1-F1-08": { kind: "unreviewed", status: "confirmed", value: "EGGTOYS" },
  "W1-F1-09": { kind: "unreviewed", status: "confirmed", value: "EnkiToy" },
  "W1-F2-01": { kind: "unreviewed", status: "confirmed", value: "冯阳昆" },
  "W1-F2-02": { kind: "unreviewed", status: "confirmed", value: "袁星亮原型工作室" },
  "W1-F2-03": { kind: "blank", status: "confirmed", value: "杰刻动漫X动物帮帮" },
  "W1-F2-04": { kind: "blank", status: "confirmed", value: "圆桌厅堂" },
  "W1-F2-05": { kind: "unreviewed", status: "confirmed", value: "BUGUSTUDIO" },
  "W1-F2-06": { kind: "blank", status: "confirmed", value: "飞佛玩具研究所" },
  "W1-F2-07": { kind: "unreviewed", status: "confirmed", value: "观妙堂" },
  "W1-F2-08": { kind: "unreviewed", status: "confirmed", value: "猿行師" },
  "W1-F3-01": { kind: "unreviewed", status: "confirmed", value: "野鸽" },
  "W1-F3-02": { kind: "unreviewed", status: "confirmed", value: "13TB" },
  "W1-F3-03": { kind: "unreviewed", status: "confirmed", value: "幽兔模玩" },
  "W1-F3-04": { kind: "unreviewed", status: "confirmed", value: "黑骑士工作室" },
  "W1-F3-05": { kind: "blank", status: "confirmed", value: "ASHMUSE烬言x青木" },
  "W1-F3-06": { kind: "unreviewed", status: "confirmed", value: "ART FUTURE12" },
  "W1-F3-07": { kind: "blank", status: "confirmed", value: "叁界蜉蝣" },
  "W1-F3-08": { kind: "unreviewed", status: "confirmed", value: "梵圣艺术" },
  "W1-F3-09": { kind: "unreviewed", status: "confirmed", value: "1000Tentacles" },
  "W1-F3-10": { kind: "unreviewed", status: "confirmed", value: "6inch+" },
  "W1-F3-11": { kind: "unreviewed", status: "confirmed", value: "ACEFIGURE" },
  "W1-F4-01": { kind: "conflict", status: "confirmed", value: "周峰山人" },
  "W1-F4-02": { kind: "unreviewed", status: "confirmed", value: "SAZEN LEE" },
  "W1-F4-03": { kind: "unreviewed", status: "confirmed", value: "起源动物协会" },
  "W1-F4-04": { kind: "unreviewed", status: "confirmed", value: "Animal Club" },
  "W1-F4-05": { kind: "unreviewed", status: "confirmed", value: "大空" },
  "W1-F4-06": { kind: "unreviewed", status: "confirmed", value: "Wonder Figure" },
  "W1-F4-07": { kind: "unreviewed", status: "confirmed", value: "CHUNK STUDIO" },
  "W1-F4-08": { kind: "conflict", status: "confirmed", value: "魔匠工坊" },
  "W1-F5-01": { kind: "unreviewed", status: "confirmed", value: "HomieToys" },
  "W1-F5-02": { kind: "unreviewed", status: "confirmed", value: "wulala" },
  "W1-F5-03": { kind: "conflict", status: "confirmed", value: "怪兽沙盒" },
  "W1-F5-04": { kind: "unreviewed", status: "confirmed", value: "Zel小则工作室" },
  "W1-F5-05": { kind: "blank", status: "confirmed", value: "白小偶&小羊64联创社" },
  "W1-F5-06": { kind: "unreviewed", status: "confirmed", value: "NAH Studio" },
  "W1-F5-07": { kind: "blank", status: "confirmed", value: "FOZN 微缩模型" },
  "W1-F5-08": { kind: "blank", status: "confirmed", value: "逃伯伯孬咪LAB" },
  "W1-F5-09": { kind: "unreviewed", status: "confirmed", value: "怪兽的沙盒" },
  "W1-F6-01": { kind: "unreviewed", status: "confirmed", value: "ADAM" },
  "W1-F6-02": { kind: "unreviewed", status: "confirmed", value: "Giveme 5ive" },
  "W1-F6-03": { kind: "unreviewed", status: "confirmed", value: "kotkas" },
  "W1-F6-04": { kind: "unreviewed", status: "confirmed", value: "MFuntoys" },
  "W1-F6-05": { kind: "unreviewed", status: "confirmed", value: "0505开发组" },
  "W1-F6-06": { kind: "unreviewed", status: "confirmed", value: "左眼皮改造所" },
  "W1-F6-07": { kind: "unreviewed", status: "confirmed", value: "归星者" },
  "W1-F6-08": { kind: "unreviewed", status: "confirmed", value: "泡面辰" },
  "W1-F6-09": { kind: "unreviewed", status: "confirmed", value: "AOC奇妙屋" },
  "W1-F6-10": { kind: "unreviewed", status: "confirmed", value: "HOWSSTUDIO好时工作室" },
  "W1-F6-11": { kind: "unreviewed", status: "confirmed", value: "三月五六日自制" },
  "W1-F6-12": { kind: "unreviewed", status: "confirmed", value: "Arnubodoll" },
  "W1-F7-01": { kind: "unreviewed", status: "confirmed", value: "grey knight" },
  "W1-F7-02": { kind: "unreviewed", status: "confirmed", value: "AXYTOYS" },
  "W1-F7-03": { kind: "unreviewed", status: "confirmed", value: "鱼Toys" },
  "W1-F7-04": { kind: "blank", status: "confirmed", value: "透SIR的妙玩工坊" },
  "W1-F7-05": { kind: "unreviewed", status: "confirmed", value: "FYJ-STUDIO" },
  "W1-F7-06": { kind: "unreviewed", status: "confirmed", value: "十二点" },
  "W1-G1-01": { kind: "unreviewed", status: "confirmed", value: "欧映工作室OUYINGSTUDIO" },
  "W1-G1-02": { kind: "unreviewed", status: "confirmed", value: "破碎的童话" },
  "W1-G1-03": { kind: "unreviewed", status: "confirmed", value: "情合坊" },
  "W1-G1-04": { kind: "unreviewed", status: "confirmed", value: "神鬼志怪系列" },
  "W1-G1-05": { kind: "unreviewed", status: "confirmed", value: "天谷工作室" },
  "W1-G1-06": { kind: "unreviewed", status: "confirmed", value: "铁条喵喵屋" },
  "W1-G1-07": { kind: "unreviewed", status: "confirmed", value: "烏蘇雲工作室" },
  "W1-G1-08": { kind: "conflict", status: "confirmed", value: "武装姬修站" },
  "W1-G1-09": {
    kind: "blank",
    status: "confirmed",
    value: "王鲁九班的日本战国raybans'sengoku period",
  },
  "W1-G1-10": { kind: "unreviewed", status: "confirmed", value: "战争公园成品模型" },
  "W1-G2-01": { kind: "unreviewed", status: "confirmed", value: "六月鹿-果冻鱼" },
  "W1-G2-02": { kind: "unreviewed", status: "confirmed", value: "轮回" },
  "W1-G2-03": { kind: "unreviewed", status: "confirmed", value: "墨工致造" },
  "W1-G2-04": { kind: "unreviewed", status: "confirmed", value: "模铸坊" },
  "W1-G2-05": { kind: "unreviewed", status: "confirmed", value: "明潮工作室" },
  "W1-G2-06": { kind: "unreviewed", status: "confirmed", value: "模创world" },
  "W1-G2-07": { kind: "unreviewed", status: "confirmed", value: "拼好模工作室" },
  "W1-G2-08": { kind: "unreviewed", status: "confirmed", value: "缪斯象限" },
  "W1-G3-01": { kind: "unreviewed", status: "confirmed", value: "鐵牛 IRONBULL" },
  "W1-G3-02": { kind: "unreviewed", status: "confirmed", value: "太阳岛" },
  "W1-G3-03": { kind: "unreviewed", status: "confirmed", value: "东莞市火山动漫" },
  "W1-G3-04": { kind: "blank", status: "confirmed", value: "东莞市火山动漫科技有限公司" },
  "W1-G3-05": { kind: "conflict", status: "confirmed", value: "唤物工作室" },
  "W1-G3-06": { kind: "unreviewed", status: "confirmed", value: "草台班子工作室" },
  "W1-G3-07": { kind: "unreviewed", status: "confirmed", value: "马也先生" },
  "W1-G3-08": { kind: "blank", status: "confirmed", value: "三陈院长办公室第二弹" },
  "W1-G3-09": { kind: "unreviewed", status: "confirmed", value: "三角犀牛" },
  "W1-G3-10": { kind: "unreviewed", status: "confirmed", value: "Gecco" },
  "W1-G4-01": { kind: "unreviewed", status: "confirmed", value: "BorisPing Toys" },
  "W1-G4-02": { kind: "unreviewed", status: "confirmed", value: "DROWING STUDIO" },
  "W1-G4-03": { kind: "unreviewed", status: "confirmed", value: "EDGExMERGANxDSBxBC" },
  "W1-G4-04": { kind: "unreviewed", status: "confirmed", value: "EWWORKS" },
  "W1-G4-05": { kind: "unreviewed", status: "confirmed", value: "FANTASY TOYS CLUB" },
  "W1-G4-06": { kind: "unreviewed", status: "confirmed", value: "Jmade" },
  "W1-G4-07": { kind: "unreviewed", status: "confirmed", value: "LYNNBOX" },
  "W1-G4-08": { kind: "unreviewed", status: "confirmed", value: "PART2PARK" },
  "W1-G4-09": { kind: "unreviewed", status: "confirmed", value: "JTSTUDIO" },
  "W1-G4-10": { kind: "unreviewed", status: "confirmed", value: "Melting House" },
  "W1-G4-11": { kind: "unreviewed", status: "confirmed", value: "Mirrfig" },
  "W1-G4-12": { kind: "unreviewed", status: "confirmed", value: "MoonCraft" },
  "W1-G5-01": { kind: "unreviewed", status: "confirmed", value: "POWERSPOTOV" },
  "W1-G5-02": { kind: "unreviewed", status: "confirmed", value: "RT toys" },
  "W1-G5-03": { kind: "unreviewed", status: "confirmed", value: "Shadow Studio" },
  "W1-G5-04": { kind: "unreviewed", status: "confirmed", value: "snow" },
  "W1-G5-05": { kind: "unreviewed", status: "confirmed", value: "SP" },
  "W1-G5-06": { kind: "unreviewed", status: "confirmed", value: "Venus Toys" },
  "W1-G5-07": { kind: "unreviewed", status: "confirmed", value: "wiztoys" },
  "W1-G5-08": { kind: "unreviewed", status: "confirmed", value: "八千工作室" },
  "W1-G5-09": { kind: "unreviewed", status: "confirmed", value: "驰野工作室" },
  "W1-G5-10": { kind: "unreviewed", status: "confirmed", value: "摆烂造物" },
  "W1-G5-11": { kind: "unreviewed", status: "confirmed", value: "炽浪工坊" },
  "W1-G5-12": { kind: "unreviewed", status: "confirmed", value: "渡鸦模型" },
  "W1-G5-13": { kind: "unreviewed", status: "confirmed", value: "锻熔" },
  "W1-G5-14": { kind: "unreviewed", status: "confirmed", value: "方寸工作室" },
  "W1-G6-01": { kind: "unreviewed", status: "confirmed", value: "鬼斧玩具" },
  "W1-G6-02": { kind: "unreviewed", status: "confirmed", value: "风模玩 Wind Toys" },
  "W1-G6-03": { kind: "unreviewed", status: "confirmed", value: "负负得胜" },
  "W1-G6-04": { kind: "unreviewed", status: "confirmed", value: "海牛工业" },
  "W1-G6-05": { kind: "unreviewed", status: "confirmed", value: "面骨不易" },
  "W1-G6-06": { kind: "unreviewed", status: "confirmed", value: "火速增兵工作室" },
  "W1-G6-07": { kind: "unreviewed", status: "confirmed", value: "锦衣聚创" },
  "W1-G6-08": { kind: "unreviewed", status: "confirmed", value: "精零锻造" },
  "W1-G6-09": { kind: "unreviewed", status: "confirmed", value: "匠狐&联合参展" },
  "W1-G6-10": { kind: "unreviewed", status: "confirmed", value: "胶雷社" },
  "W1-G6-11": { kind: "unreviewed", status: "confirmed", value: "老爹爹潮玩OPAPA TOYS" },
  "W1-G6-12": { kind: "unreviewed", status: "confirmed", value: "双杠工作室" },
  "W1-G7-01": { kind: "unreviewed", status: "confirmed", value: "童山ART" },
  "W1-G7-02": { kind: "unreviewed", status: "confirmed", value: "奥特曼墓场" },
  "W1-G7-03": { kind: "unreviewed", status: "confirmed", value: "棱光折射PrismRefraction" },
  "W1-G7-04": { kind: "unreviewed", status: "confirmed", value: "猫车王俱乐部" },
  "W1-G7-05": { kind: "unreviewed", status: "confirmed", value: "一窟鬼模造" },
  "W1-G7-06": { kind: "unreviewed", status: "confirmed", value: "造曾人" },
  "W1-G7-07": { kind: "unreviewed", status: "confirmed", value: "造物者" },
  "W1-G7-08": { kind: "unreviewed", status: "confirmed", value: "治镐" },
  "W1-G7-09": { kind: "unreviewed", status: "confirmed", value: "REBORN(重生工作室)" },
  "W1-G7-10": { kind: "unreviewed", status: "confirmed", value: "龙栖构筑Studio" },
  "W1-G7-11": { kind: "unreviewed", status: "confirmed", value: "龍瞳造物" },
  "W1-H1-01": { kind: "conflict", status: "confirmed", value: "小犬工作室" },
  "W1-H1-02": { kind: "unreviewed", status: "confirmed", value: "春雨工作室" },
  "W1-H1-03": { kind: "unreviewed", status: "confirmed", value: "EXHU工坊" },
  "W1-H1-04": { kind: "unreviewed", status: "confirmed", value: "shiki四季工坊" },
  "W1-H1-05": { kind: "unreviewed", status: "confirmed", value: "LIPTON STUDIO" },
  "W1-H1-06": { kind: "unreviewed", status: "confirmed", value: "NERV A.W.D" },
  "W1-H1-07": { kind: "unreviewed", status: "confirmed", value: "捕人夹" },
  "W1-H1-08": { kind: "unreviewed", status: "confirmed", value: "不可思议猫" },
  "W1-H1-09": { kind: "unreviewed", status: "confirmed", value: "山鲸鱼的模型小摊" },
  "W1-H1-10": { kind: "unreviewed", status: "confirmed", value: "无情削刀手" },
  "W1-H1-11": { kind: "conflict", status: "confirmed", value: "無奇工作室" },
  "W1-H1-12": { kind: "unreviewed", status: "confirmed", value: "JA Studio捷艾模型工作室" },
  "W1-H2-01": { kind: "unreviewed", status: "confirmed", value: "TYGTOY" },
  "W1-H2-02": { kind: "unreviewed", status: "confirmed", value: "老清新玩具" },
  "W1-H2-03": { kind: "unreviewed", status: "confirmed", value: "百小鬼" },
  "W1-H2-04": { kind: "unreviewed", status: "confirmed", value: "Iron Heart" },
  "W1-H2-05": { kind: "unreviewed", status: "confirmed", value: "ONE OFF MUSEUM" },
  "W1-H2-06": { kind: "unreviewed", status: "confirmed", value: "恶龙工作室" },
  "W1-H2-07": { kind: "unreviewed", status: "confirmed", value: "D1S神祇一号工作室" },
  "W1-H2-08": { kind: "unreviewed", status: "confirmed", value: "入画Atelier" },
  "W1-H2-09": { kind: "unreviewed", status: "confirmed", value: "极彩铸物" },
  "W1-H2-10": { kind: "unreviewed", status: "confirmed", value: "ASTRA STUDIO" },
  "W1-H2-11": { kind: "unreviewed", status: "confirmed", value: "H.Z." },
  "W1-H2-12": { kind: "unreviewed", status: "confirmed", value: "黑炎工房" },
  "W1-H2-13": { kind: "unreviewed", status: "confirmed", value: "伏都造物" },
  "W1-H3-01": { kind: "unreviewed", status: "confirmed", value: "猫老弟工作室" },
  "W1-H3-02": { kind: "unreviewed", status: "confirmed", value: "㍿絶対色域デザイン研究所" },
  "W1-H3-03": { kind: "unreviewed", status: "confirmed", value: "易儒涂装" },
  "W1-H3-04": { kind: "unreviewed", status: "confirmed", value: "克拉夫特" },
  "W1-H3-05": { kind: "unreviewed", status: "confirmed", value: "Novel Star" },
  "W1-H3-06": { kind: "unreviewed", status: "confirmed", value: "SHINYSTARLIGHT" },
  "W1-H3-07": { kind: "unreviewed", status: "confirmed", value: "U235核燃动力" },
  "W1-H3-08": { kind: "unreviewed", status: "confirmed", value: "黑白格" },
  "W1-H3-09": { kind: "unreviewed", status: "confirmed", value: "空想" },
  "W1-H3-10": { kind: "unreviewed", status: "confirmed", value: "歪狸谷" },
  "W1-H3-11": { kind: "unreviewed", status: "confirmed", value: "Gold & Silver Society" },
  "W1-H4-01": { kind: "unreviewed", status: "confirmed", value: "六扇门" },
  "W1-H4-02": { kind: "unreviewed", status: "confirmed", value: "奇力玩具屋" },
  "W1-H4-03": { kind: "conflict", status: "confirmed", value: "梵境FancyRealm" },
  "W1-H4-04": { kind: "conflict", status: "confirmed", value: "君卿工作室" },
  "W1-H4-05": { kind: "unreviewed", status: "confirmed", value: "狗造社" },
  "W1-H4-06": { kind: "unreviewed", status: "confirmed", value: "狐唬虎工作室" },
  "W1-H4-07": { kind: "unreviewed", status: "confirmed", value: "雷飞船的大熊猫" },
  "W1-H5-01": { kind: "unreviewed", status: "confirmed", value: "freewillstudio" },
  "W1-H5-02": { kind: "unreviewed", status: "confirmed", value: "IMAGERY意像" },
  "W1-H5-03": { kind: "unreviewed", status: "confirmed", value: "TNTNT" },
  "W1-H5-04": { kind: "unreviewed", status: "confirmed", value: "桃山甘露园" },
  "W1-H5-05": { kind: "unreviewed", status: "confirmed", value: "斯丁格文化" },
  "W1-H5-06": { kind: "unreviewed", status: "confirmed", value: "退社后胶time" },
  "W1-H5-07": { kind: "unreviewed", status: "confirmed", value: "星程工作室" },
  "W1-H5-08": { kind: "unreviewed", status: "confirmed", value: "PACEXS" },
  "W1-H5-09": { kind: "unreviewed", status: "confirmed", value: "Hini十三的小摊" },
  "W1-H5-10": { kind: "unreviewed", status: "confirmed", value: "BOOH" },
  "W1-H6-01": { kind: "unreviewed", status: "confirmed", value: "原型启动" },
  "W1-H6-02": { kind: "unreviewed", status: "confirmed", value: "ainav&aca21" },
  "W1-H6-03": { kind: "unreviewed", status: "confirmed", value: "安以佑的涂装小铺" },
  "W1-H6-04": { kind: "unreviewed", status: "confirmed", value: "DOOM2DAY_ZONE" },
  "W1-H6-05": { kind: "unreviewed", status: "confirmed", value: "Modelpia" },
  "W1-H6-06": { kind: "unreviewed", status: "confirmed", value: "皮球制PQSTUDIO" },
  "W1-H6-07": { kind: "unreviewed", status: "confirmed", value: "一个早做打算大战三个死线战士" },
  "W1-H6-08": { kind: "unreviewed", status: "confirmed", value: "问工房" },
  "W1-H6-09": { kind: "unreviewed", status: "confirmed", value: "啤库尼库工房" },
  "W1-H6-10": { kind: "unreviewed", status: "confirmed", value: "赛博拼摊" },
  "W1-H7-01": { kind: "unreviewed", status: "confirmed", value: "半拉手艺人" },
  "W1-H7-02": { kind: "unreviewed", status: "confirmed", value: "Dream Gallery" },
  "W1-H7-03": { kind: "unreviewed", status: "confirmed", value: "Hist模型社" },
  "W1-H7-04": { kind: "conflict", status: "confirmed", value: "iDUOi Studio" },
  "W1-H7-05": { kind: "unreviewed", status: "confirmed", value: "LeiChing" },
  "W1-H7-06": { kind: "unreviewed", status: "confirmed", value: "LEI工作室" },
  "W1-H7-07": { kind: "unreviewed", status: "confirmed", value: "MK微缩王国" },
  "W1-H7-08": { kind: "unreviewed", status: "confirmed", value: "稻草人模型" },
};
